#!/usr/bin/env python3
# regenerates api/_lib/dc_ranges.py from the official cloud provider ip lists.
# run it once in a while (or before a deploy) with: .venv/bin/python scripts/update_dc_ranges.py
# the module it writes is data only, the lookup logic lives in api/_lib/botcheck.py
import base64
import ipaddress
import json
import struct
import sys
import urllib.request
import zlib
from datetime import date
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "api" / "_lib" / "dc_ranges.py"

# provider name -> (url, parser). parsers yield cidr strings
SOURCES = {
    "aws": ("https://ip-ranges.amazonaws.com/ip-ranges.json", "aws"),
    "gcp": ("https://www.gstatic.com/ipranges/cloud.json", "gcp"),
    "oracle": ("https://docs.oracle.com/iaas/tools/public_ip_ranges.json", "oracle"),
    "digitalocean": ("https://digitalocean.com/geo/google.csv", "csv"),
    "linode": ("https://geoip.linode.com/", "csv"),
    "vultr": ("https://geofeed.constant.com/", "csv"),
}


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "lynka-dc-ranges/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse(kind: str, raw: bytes):
    if kind == "aws":
        data = json.loads(raw)
        for item in data.get("prefixes", []):
            yield item["ip_prefix"]
        for item in data.get("ipv6_prefixes", []):
            yield item["ipv6_prefix"]
    elif kind == "gcp":
        data = json.loads(raw)
        for item in data.get("prefixes", []):
            cidr = item.get("ipv4Prefix") or item.get("ipv6Prefix")
            if cidr:
                yield cidr
    elif kind == "oracle":
        data = json.loads(raw)
        for region in data.get("regions", []):
            for item in region.get("cidrs", []):
                yield item["cidr"]
    elif kind == "csv":
        # geofeed style: cidr,country,region,city per line, comments with #
        for line in raw.decode("utf-8", "replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            yield line.split(",", 1)[0].strip()


def main() -> int:
    v4: list[ipaddress.IPv4Network] = []
    v6: list[ipaddress.IPv6Network] = []
    counts = {}
    for name, (url, kind) in SOURCES.items():
        try:
            raw = fetch(url)
        except Exception as err:
            print(f"skip {name}: {err}", file=sys.stderr)
            counts[name] = 0
            continue
        n = 0
        for cidr in parse(kind, raw):
            try:
                net = ipaddress.ip_network(cidr, strict=False)
            except ValueError:
                continue
            if net.is_private:
                continue
            (v4 if net.version == 4 else v6).append(net)
            n += 1
        counts[name] = n
        print(f"{name}: {n} prefixes")

    if not v4:
        print("no v4 data fetched, refusing to write an empty module", file=sys.stderr)
        return 1

    merged4 = list(ipaddress.collapse_addresses(v4))
    merged6 = list(ipaddress.collapse_addresses(v6))

    packed4 = b"".join(
        struct.pack(">II", int(n.network_address), int(n.broadcast_address))
        for n in merged4
    )
    packed6 = b"".join(
        int(n.network_address).to_bytes(16, "big")
        + int(n.broadcast_address).to_bytes(16, "big")
        for n in merged6
    )
    blob4 = base64.b85encode(zlib.compress(packed4, 9)).decode()
    blob6 = base64.b85encode(zlib.compress(packed6, 9)).decode()

    src_line = ", ".join(f"{k} {v}" for k, v in counts.items())
    body = [
        "# generated by scripts/update_dc_ranges.py, do not edit by hand",
        f"# {date.today().isoformat()}: {src_line}",
        f"# merged: {len(merged4)} v4 ranges, {len(merged6)} v6 ranges",
        "# packed as zlib(start/end address pairs), decoded in botcheck.py",
        f'V4 = "{blob4}"',
        f'V6 = "{blob6}"',
        "",
    ]
    OUT.write_text("\n".join(body))
    kb = OUT.stat().st_size // 1024
    print(f"wrote {OUT} ({kb} kb, {len(merged4)} v4 + {len(merged6)} v6 ranges)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
